---
- name: Install Docker and Docker Compose on Red Hat 7 server
  hosts: redhat7_server
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Remove existing Docker package if present
      yum:
        name: docker
        state: absent

    - name: Remove existing Docker common package if present
      yum:
        name: docker-common
        state: absent

    - name: Add Docker repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        enabled: yes
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install Docker CE
      yum:
        name: docker-ce
        state: latest
      register: docker_install

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      when: docker_install.changed

    - name: Ensure Python 3 is installed
      yum:
        name: python3
        state: present

    - name: Ensure pip3 is installed
      package:
        name: python3-pip
        state: present

    - name: Ensure pip is installed
      package:
        name: python-pip
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present
        executable: pip3
